models/alert.py
from typing import Dict
from dataclasses import dataclass, field
from libs.mailgun import Mailgun
from models.item import Item
from uuid import uuid4
from models.model import Model
from models.user import User


@dataclass(eq=False)
class Alert(Model):
    collection: str = field(init=False, default="alerts")
    name: str
    item_id: str
    price_limit: float
    user_email: str
    _id: str = field(default_factory=lambda: uuid4().hex)

    def __post_init__(self):
        self.item = Item.get_by_id(self.item_id)
        self.user = User.find_by_email(self.user_email)

    def json(self) -> Dict:
        return {
            '_id': self._id,
            'name': self.name,
            'item_id': self.item_id,
            'price_limit': self.price_limit,
            'user_email': self.user_email
        }

    def load_item_price(self):
        self.item.load_price()
        return self.item.price

    def notify_if_price_reached(self):
        if self.item.price < self.price_limit:
            print(f'Item {self.item} has reached a price under {self.price_limit}. Latest price: {self.item.price}.')
            Mailgun.send_mail(
                [self.user_email],
                f'Notification for {self.name}',
                f'Your alert {self.name} has reached a price under {self.price_limit}. The latest price'
                f' is {self.item.price}. Go to this address to check your item: {self.item.url}.',
                f'<p>Your alert {self.name} has reached a price under {self.price_limit}. The latest price'
                f' is {self.item.price}.</p><p>Click <a href="{self.item.url}">here</a> to purchase your item.</p>'
            )

views/alerts.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from models.alert import Alert
from models.item import Item
from models.store import Store
from models.user import requires_login

alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/')
@requires_login
def index():
    alerts = Alert.find_many_by('user_email', session['email'])
    return render_template('alerts/index.html', alerts=alerts)


@alert_blueprint.route('/new', methods=['GET', 'POST'])
@requires_login
def new_alert():
    if request.method == 'POST':
        alert_name = request.form['name']
        item_url = request.form['item_url']
        price_limit = float(request.form['price_limit'])

        store = Store.find_by_url(item_url)
        item = Item(item_url, store.tag_name, store.query)
        item.load_price()
        item.save_to_mongo()

        Alert(alert_name, item._id, price_limit, session['email']).save_to_mongo()
    return render_template('alerts/new_alert.html')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)

    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])

        alert.price_limit = price_limit
        alert.save_to_mongo()

        return redirect(url_for('.index'))

    return render_template('alerts/edit_alert.html', alert=alert)


@alert_blueprint.route('/delete/<string:alert_id>')
@requires_login
def delete_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if alert.user_email == session['email']:
        alert.remove_from_mongo()
    return redirect(url_for('.index'))

templates/alerts/edit_alert.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Update Alert</h1></header>
    <section class="update-alert-form">
        <form method="post">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" value="{{ alert.name }}" disabled />
            </div>
            <div class="form-group">
                <label for="item_url">Item URL</label>
                <input type="text" class="form-control" id="item_url" name="item_url" value="{{ alert.item.url }}" disabled />
            </div>
            <div class="create-item-form">
                <label for="price_limit">Price limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder='120'
                       value="{{ alert.price_limit }}" aria-describedby="priceLimitHelp"/>
                <small class="form-text text-muted" id="priceLimitHelp">
                    Under which price for the item would you like to get notified?
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </section>
{% endblock %}

templates/alerts/index.html
{% extends "base.html" %}

{% block content %}
<header>
    <h1>Alerts</h1>
</header>
<section>
    <div class="list-group mb-3">
        {% for alert in alerts %}
            <div class="list-group-item">
                <h4>{{ alert.name }}</h4>
                <p>
                    <a href="{{alert.item.url}}">{{ alert.item_id }} (last price {{ alert.item.price }} pounds.)</a>
                </p>
                <a class="btn btn-secondary" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}">
                    Edit
                </a>
                <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}">
                    Delete
                </a>
            </div>
        {% endfor %}
    </div>
    <a class="btn btn-primary" href="{{ url_for('alerts.new_alert') }}">
        Create new
    </a>
</section>
{% endblock %}

templates/alerts/new_alert.html
{% extends "base.html" %}

{% block content %}
    <header><h1>Create Alert</h1></header>
    <section class="create-alert-form">
        <form method="post">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Surface Pro 6" />
            </div>
            <div class="form-group">
                <label for="item_url">Item URL</label>
                <input type="text" class="form-control" id="item_url" name="item_url" />
            </div>
            <div class="create-item-form">
                <label for="price_limit">Price limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder='120'
                       aria-describedby="priceLimitHelp"/>
                <small class="form-text text-muted" id="priceLimitHelp">
                    Under which price for the item would you like to get notified?
                </small>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </section>
{% endblock %}